---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: topolvm-thin-provisioner
  resources:
    requests:
      storage: 100Gi
