---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: opencode-secret
    template:
      engineVersion: v2
      data:
        OPENCODE_SERVER_PASSWORD: "{{ .OPENCODE_SERVER_PASSWORD }}"
  data:
    - secretKey: OPENCODE_SERVER_PASSWORD
      remoteRef:
        key: opencode
        property: OPENCODE_SERVER_PASSWORD
