---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  # - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  # - ./crossplane.yaml
  # - ./crunchydata.yaml
  # - ./descheduler.yaml
  # - ./emqx.yaml
  - ./emberstack.yaml
  - ./external-dns.yaml
  - ./bitwarden-eso.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  # - ./intel.yaml
  - ./jetstack.yaml
  # - ./kyverno.yaml
  # - ./metrics-server.yaml
  # - ./node-feature-discovery.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  # - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  # - ./spegel.yaml
  - ./stakater.yaml
  - ./tailscale.yaml
  # - ./kubernetes-dashboard.yaml
  - ./hajimari.yaml
  - ./prefect.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./topolvm.yaml
  - ./local-path-provisioner.yaml
  - ./nextcloud.yaml
