---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-automated-nfs
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: topolvm-thin-provisioner
  resources:
    requests:
      storage: 20Gi
